//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handl.UiPath.Handl.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Handl.UiPath.Handl.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action on a document.
        /// </summary>
        public static string ActionDescription {
            get {
                return ResourceManager.GetString("ActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Documents separated by commas, e.g. &quot;passport_main,bank_card&quot;. Empty field allows all docs. More at: https://latest.dbrain.io/docs/document-types-and-fields/.
        /// </summary>
        public static string AllowedDocsDescription {
            get {
                return ResourceManager.GetString("AllowedDocsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Documents.
        /// </summary>
        public static string AllowedDocsName {
            get {
                return ResourceManager.GetString("AllowedDocsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway for Docr server (do not specify if you want to use the cloud version).
        /// </summary>
        public static string ApiGatewayDescription {
            get {
                return ResourceManager.GetString("ApiGatewayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Gateway.
        /// </summary>
        public static string ApiGatewayName {
            get {
                return ResourceManager.GetString("ApiGatewayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token for API.
        /// </summary>
        public static string ApiTokenDescription {
            get {
                return ResourceManager.GetString("ApiTokenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API token.
        /// </summary>
        public static string ApiTokenName {
            get {
                return ResourceManager.GetString("ApiTokenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handl.
        /// </summary>
        public static string Handl {
            get {
                return ResourceManager.GetString("Handl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify &amp; recognize documents.
        /// </summary>
        public static string HandlDescription {
            get {
                return ResourceManager.GetString("HandlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handl for documents.
        /// </summary>
        public static string HandlName {
            get {
                return ResourceManager.GetString("HandlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html demo page.
        /// </summary>
        public static string HtmlDescription {
            get {
                return ResourceManager.GetString("HtmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        public static string HtmlName {
            get {
                return ResourceManager.GetString("HtmlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input image with document for classification &amp; recognition.
        /// </summary>
        public static string ImageDescription {
            get {
                return ResourceManager.GetString("ImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result in json.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result message in JSON format.
        /// </summary>
        public static string ResultDescription {
            get {
                return ResourceManager.GetString("ResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultName {
            get {
                return ResourceManager.GetString("ResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout to wait response from servers. Keep in mind that enabling HITL increases timeout significantly.
        /// </summary>
        public static string TimeoutDescription {
            get {
                return ResourceManager.GetString("TimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (s).
        /// </summary>
        public static string TimeoutName {
            get {
                return ResourceManager.GetString("TimeoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Handl HITL to improve quality. Recognition may require more time..
        /// </summary>
        public static string WithHitlDescription {
            get {
                return ResourceManager.GetString("WithHitlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Handl Human-in-the-loop.
        /// </summary>
        public static string WithHitlName {
            get {
                return ResourceManager.GetString("WithHitlName", resourceCulture);
            }
        }
    }
}
